---
apiVersion: v1
kind: Service
metadata:
  name: webecho
  labels:
    name: webecho
spec:
  type: NodePort
  ports:
  - name: webecho-port
    port: 8080
    nodePort: 30087
  selector:
    name: webecho
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webecho
spec:
  replicas: 2
  selector:
    matchLabels:
      name: "webecho"
  template:
    metadata:
      labels:
        "name": "webecho"
    spec:
      containers:
      - name: webecho-container
        image: registry.hundsun.com/hcs/web_echo:0.1
        ports:
        - containerPort: 8080
          name: webecho-port
